// <auto-generated />
using System;
using Kernel.EF.Demo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kernel.EF.Migrations
{
    [DbContext(typeof(ReportServerContext))]
    [Migration("20200411134433_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kernel.EF.Demo.Roles", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnName("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<byte>("RoleFlags")
                        .HasColumnType("tinyint");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(260)")
                        .HasMaxLength(260);

                    b.Property<string>("TaskMask")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("RoleId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasName("IX_Roles")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Kernel.EF.Demo.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnName("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthType")
                        .HasColumnType("int");

                    b.Property<byte[]>("Sid")
                        .HasColumnType("varbinary(85)")
                        .HasMaxLength(85);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(260)")
                        .HasMaxLength(260);

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("Sid", "UserName", "AuthType")
                        .IsUnique()
                        .HasName("IX_Users")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
